version: 2

jobs:
  build:
    machine:
      enabled: true
    branches:
      only:
        - master
    steps:
      - checkout
      - run: |
          make build && make release TAG=$(echo $CIRCLE_SHA1 | cut -c -7) || exit 1
