version: 2

jobs:
  build:
    machine:
      enabled: true
    branches:
      only:
        - master
    steps:
      - setup_remote_docker
      - run: |
          make build && make release || exit 1
